language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - |
    # not all dependencies advertise PHP 8 support yet
    composer config platform.php 7.4.0
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# php-coveralls does not support PHP 8 yet:
# https://github.com/php-coveralls/php-coveralls/issues/281

#after_script:
#  - vendor/bin/php-coveralls -v
